spring: 
  profiles:
    active:
    - dev

---  
spring:
  profiles: dev			#开发环境
  application:
    name: springcloud-config-sszy-dev

---
spring:
  profiles: test			#测试环境
  application:
    name: springcloud-config-sszy-test
 
 ---  
spring:
  profiles: dev			#开发环境
  application:
    name: springcloud-config-sszy-uat

---
spring:
  profiles: test			#测试环境
  application:
    name: springcloud-config-sszy-release

