server: 
  port: 3388 
spring:
  profiles:
    active: test
profile: 你就 是一个2b ,2222
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: sszycloud-config-client-eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
profile: 你就 是一个2b ,你还不承认

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: sszycloud-config-client-eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

profile: h---asdfadadsl33333333