server: 
  port: 3388 
spring:
  profiles:
    active: test
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: sszycloud-config-client-eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
profile: 塔顶 阿斯蒂芬工本 天天向上,好好学习

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: sszycloud-config-client-eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

profile: h---asdfadadsl33333333